CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('no', 'onproses', 'close')) DEFAULT 'no',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  messages JSONB DEFAULT '[]'::jsonb,
  "order" JSONB DEFAULT '[]'::jsonb
);

-- =================================================================
-- SKEMA DATABASE LOGISTICS STUDIO & BARANG PROMOSI
-- =================================================================
CREATE TABLE IF NOT EXISTS public.jenis (
    id VARCHAR(100) PRIMARY KEY,
    kode VARCHAR(50) NOT NULL,
    nama VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tujuan (
    id VARCHAR(100) PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota VARCHAR(100) DEFAULT '',
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.pengirim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota_kab VARCHAR(100) DEFAULT '',
    telp VARCHAR(50) DEFAULT '',
    kota_dateline VARCHAR(100) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.documents (
    id VARCHAR(100) PRIMARY KEY,
    nomor_sj VARCHAR(100) NOT NULL UNIQUE,
    jenis_id VARCHAR(100) REFERENCES public.jenis(id) ON DELETE SET NULL,
    tanggal DATE NOT NULL,
    tujuan_id VARCHAR(100) REFERENCES public.tujuan(id) ON DELETE SET NULL,
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.items (
    id VARCHAR(100) PRIMARY KEY,
    doc_id VARCHAR(100) REFERENCES public.documents(id) ON DELETE CASCADE,
    rekap_no INT NOT NULL,
    nama_barang VARCHAR(255) NOT NULL,
    ctn INT DEFAULT 0,
    pcs INT DEFAULT 0,
    berat NUMERIC(10,2) DEFAULT 0,
    kubikasi NUMERIC(10,3) DEFAULT 0,
    keterangan TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.promosi (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nomor VARCHAR(100) NOT NULL,
    tgl_terima DATE NOT NULL,
    material TEXT NOT NULL,
    pengirim VARCHAR(255) DEFAULT '',
    penerima VARCHAR(255) DEFAULT '',
    nopol VARCHAR(50) DEFAULT '',
    expedisi VARCHAR(100) DEFAULT '',
    keterangan TEXT DEFAULT '',
    jumlah_ctn INT DEFAULT 0,
    jumlah_pcs INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.rekapan_sj (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    judul VARCHAR(255) NOT NULL,
    tanggal_rekap TIMESTAMPTZ DEFAULT NOW(),
    total_sj INT DEFAULT 0,
    total_item INT DEFAULT 0,
    total_ctn INT DEFAULT 0,
    total_pcs INT DEFAULT 0,
    total_berat NUMERIC(10,2) DEFAULT 0,
    total_kubikasi NUMERIC(10,3) DEFAULT 0,
    data_detail JSONB DEFAULT '[]'::jsonb,
    keterangan TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =================================================================
-- SKEMA TABEL BROADCAST / SIARAN ANTAR PERANGKAT PUBLIK
-- =================================================================
CREATE TABLE IF NOT EXISTS public.broadcast_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'info', -- 'info', 'urgent', 'warning', 'announcement'
    device_info VARCHAR(100) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert admin user jika belum ada
INSERT INTO users (email, password) 
VALUES ('admin@admin.com', 'Kino.2026') 
ON CONFLICT (email) DO NOTHING;

-- Insert default announcements jika belum ada
INSERT INTO settings (id, messages) 
VALUES ('announcements', '[]'::jsonb) 
ON CONFLICT (id) DO NOTHING;

-- Seed Jenis SJ
INSERT INTO public.jenis (id, kode, nama)
VALUES ('jenis-1', 'CKB', 'SURAT JALAN CKB')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Pengirim
INSERT INTO public.pengirim (nama, alamat, kota_kab, telp, kota_dateline)
SELECT 'LOGISTICS WAREHOUSE', 'Jl. Utama Logistics No. 1', 'Jakarta', '021-12345678', 'Jakarta'
WHERE NOT EXISTS (SELECT 1 FROM public.pengirim);

-- =================================================================
-- SKEMA TABEL RETUR INVENTORY & MONITORING PEMUSNAHAN
-- =================================================================
CREATE TABLE IF NOT EXISTS public.retur_inventory (
    id VARCHAR(100) PRIMARY KEY,
    no_pengajuan VARCHAR(100) NOT NULL,
    tgl_pengajuan DATE NOT NULL,
    customer_distributor VARCHAR(255) NOT NULL,
    sku_code VARCHAR(100) NOT NULL,
    material_desc TEXT NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    expired_date DATE,
    qty_retur_pcs NUMERIC(15,2) DEFAULT 0,
    cogs_per_unit NUMERIC(15,2) DEFAULT 0,
    total_cogs_retur NUMERIC(18,2) DEFAULT 0,
    alasan_retur TEXT NOT NULL,
    kategori_retur VARCHAR(50) DEFAULT 'ED_NEAR', -- 'ED_NEAR', 'RUSAK_KEMASAN', 'RECALL', 'OVERSTOCK', 'LAINNYA'
    status VARCHAR(50) DEFAULT 'MENUNGGU_APPROVAL', -- 'MENUNGGU_APPROVAL', 'DISETUJUI', 'DITOLAK', 'DALAM_PROSES_GUDANG', 'SELESAI_MASUK_GUDANG', 'SIAP_MUSNAH'
    lokasi_gudang_terima VARCHAR(100) DEFAULT 'WH-CKB',
    no_surat_jalan_retur VARCHAR(100) DEFAULT '',
    no_dokumen_sap VARCHAR(100) DEFAULT '',
    disetujui_oleh VARCHAR(100) DEFAULT '',
    tgl_approval TIMESTAMPTZ,
    pic_gudang VARCHAR(100) DEFAULT '',
    catatan_retur TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_update TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.monitoring_pemusnahan (
    id VARCHAR(100) PRIMARY KEY,
    tahun INT NOT NULL,
    bulan_pengajuan VARCHAR(150) NOT NULL,
    qty_pcs NUMERIC(15,2) DEFAULT 0,
    value NUMERIC(18,2) DEFAULT 0,
    cogs NUMERIC(18,2) DEFAULT 0,
    sloc VARCHAR(50) DEFAULT '8A04',
    location VARCHAR(100) DEFAULT 'Cikembar',
    kategori VARCHAR(100) DEFAULT 'REGULER',
    no_persetujuan VARCHAR(150) DEFAULT '',
    no_pengajuan VARCHAR(150) DEFAULT '',
    no_penolakan_qa VARCHAR(150) DEFAULT '',
    approved_head_log VARCHAR(255) DEFAULT '',
    approved_ho_direksi VARCHAR(255) DEFAULT '',
    serah_terima_gudang_reject VARCHAR(255) DEFAULT '',
    acc_teams_bap VARCHAR(255) DEFAULT '',
    kirim_dokumen_bap_ke_ho VARCHAR(20) DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    musnah_sistem_z87 VARCHAR(255) DEFAULT '',
    completed_approval VARCHAR(20) DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    completed_ba VARCHAR(20) DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    completed_migo VARCHAR(20) DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    sj_kapsul VARCHAR(150) DEFAULT '',
    bap_kapsul VARCHAR(150) DEFAULT '',
    check_kapsul VARCHAR(20) DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    keterangan TEXT DEFAULT '',
    status VARCHAR(50) DEFAULT 'PROSES', -- 'SELESAI', 'PROSES'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_update TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- AKSES HAK AKSES & RLS (Row Level Security)
-- =========================================================
ALTER TABLE links DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.jenis DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tujuan DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengirim DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.promosi DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rekapan_sj DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcast_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.retur_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_pemusnahan DISABLE ROW LEVEL SECURITY;

-- Berikan izin akses penuh ke anon & authenticated
GRANT ALL ON TABLE public.broadcast_messages TO anon, authenticated;
GRANT ALL ON TABLE public.retur_inventory TO anon, authenticated;
GRANT ALL ON TABLE public.monitoring_pemusnahan TO anon, authenticated;

-- Aktifkan Realtime Replication untuk tabel broadcast_messages, retur_inventory, monitoring_pemusnahan
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'broadcast_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.broadcast_messages;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'retur_inventory'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.retur_inventory;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'monitoring_pemusnahan'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.monitoring_pemusnahan;
  END IF;
EXCEPTION WHEN OTHERS THEN
  -- Abaikan jika publication supabase_realtime belum aktif atau sudah ada
  NULL;
END $$;




