CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('no', 'onproses', 'close')) DEFAULT 'no',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  messages JSONB DEFAULT '[]'::jsonb,
  "order" JSONB DEFAULT '[]'::jsonb
);

-- =================================================================
-- SKEMA DATABASE LOGISTICS STUDIO & BARANG PROMOSI
-- =================================================================
CREATE TABLE IF NOT EXISTS public.jenis (
    id VARCHAR(100) PRIMARY KEY,
    kode VARCHAR(50) NOT NULL,
    nama VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tujuan (
    id VARCHAR(100) PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota VARCHAR(100) DEFAULT '',
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.pengirim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota_kab VARCHAR(100) DEFAULT '',
    telp VARCHAR(50) DEFAULT '',
    kota_dateline VARCHAR(100) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.documents (
    id VARCHAR(100) PRIMARY KEY,
    nomor_sj VARCHAR(100) NOT NULL UNIQUE,
    jenis_id VARCHAR(100) REFERENCES public.jenis(id) ON DELETE SET NULL,
    tanggal DATE NOT NULL,
    tujuan_id VARCHAR(100) REFERENCES public.tujuan(id) ON DELETE SET NULL,
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.items (
    id VARCHAR(100) PRIMARY KEY,
    doc_id VARCHAR(100) REFERENCES public.documents(id) ON DELETE CASCADE,
    rekap_no INT NOT NULL,
    nama_barang VARCHAR(255) NOT NULL,
    ctn INT DEFAULT 0,
    pcs INT DEFAULT 0,
    berat NUMERIC(10,2) DEFAULT 0,
    kubikasi NUMERIC(10,3) DEFAULT 0,
    keterangan TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.promosi (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nomor VARCHAR(100) NOT NULL,
    tgl_terima DATE NOT NULL,
    material TEXT NOT NULL,
    pengirim VARCHAR(255) DEFAULT '',
    penerima VARCHAR(255) DEFAULT '',
    nopol VARCHAR(50) DEFAULT '',
    expedisi VARCHAR(100) DEFAULT '',
    keterangan TEXT DEFAULT '',
    jumlah_ctn INT DEFAULT 0,
    jumlah_pcs INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert admin user jika belum ada
INSERT INTO users (email, password) 
VALUES ('admin@admin.com', 'Kino.2026') 
ON CONFLICT (email) DO NOTHING;

-- Insert default announcements jika belum ada
INSERT INTO settings (id, messages) 
VALUES ('announcements', '[]'::jsonb) 
ON CONFLICT (id) DO NOTHING;

-- Seed Jenis SJ
INSERT INTO public.jenis (id, kode, nama)
VALUES ('jenis-1', 'CKB', 'SURAT JALAN CKB')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Pengirim
INSERT INTO public.pengirim (nama, alamat, kota_kab, telp, kota_dateline)
SELECT 'LOGISTICS WAREHOUSE', 'Jl. Utama Logistics No. 1', 'Jakarta', '021-12345678', 'Jakarta'
WHERE NOT EXISTS (SELECT 1 FROM public.pengirim);

-- =========================================================
-- AKSES HAK AKSES & RLS (Row Level Security)
-- =========================================================
ALTER TABLE links DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.jenis DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tujuan DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengirim DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.promosi DISABLE ROW LEVEL SECURITY;


