-- =================================================================
-- SKEMA TABEL USERS & AUTENTIKASI BARU (PostgreSQL / Supabase)
-- =================================================================
-- 1. Aktifkan ekstensi pendukung (opsional jika belum aktif)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Fungsi trigger untuk otomatis memperbarui kolom updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Pembuatan Tabel USERS
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    username VARCHAR(100) UNIQUE NOT NULL,
    nama VARCHAR(255) NOT NULL,
    pin VARCHAR(20) NOT NULL,                    -- PIN 4-6 digit (atau hashed password)
    avatar TEXT DEFAULT '',
    role VARCHAR(50) NOT NULL DEFAULT 'Pelaksana', -- 'Admin' | 'Pelaksana'
    status VARCHAR(50) NOT NULL DEFAULT 'Aktif',   -- 'Aktif' | 'Nonaktif'
    email_google VARCHAR(255) DEFAULT '',
    permissions JSONB NOT NULL DEFAULT '{
        "canInputIncoming": true,
        "canTally": true,
        "canEditMasterBarang": false,
        "canManageUsers": false,
        "canApproveQC": false,
        "canAccessDatabase": false
    }'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Pastikan kolom baru terpasang jika tabel users sudah ada sebelumnya
ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS nama VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pin VARCHAR(20) DEFAULT '123456',
    ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'Pelaksana',
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Aktif',
    ADD COLUMN IF NOT EXISTS email_google VARCHAR(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS permissions JSONB DEFAULT '{
        "canInputIncoming": true,
        "canTally": true,
        "canEditMasterBarang": false,
        "canManageUsers": false,
        "canApproveQC": false,
        "canAccessDatabase": false
    }'::jsonb;

-- 4. Indexing untuk mempercepat query pencarian login
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON public.users(status);

-- 5. Pasang Trigger auto-update timestamp
DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 6. Seed Data: Akun Admin Default Awal
INSERT INTO public.users (id, username, nama, pin, role, status, permissions)
VALUES (
    'usr-admin-default',
    'admin',
    'Administrator Utama',
    '123456',
    'Admin',
    'Aktif',
    '{
        "canInputIncoming": true,
        "canTally": true,
        "canEditMasterBarang": true,
        "canManageUsers": true,
        "canApproveQC": true,
        "canAccessDatabase": true
    }'::jsonb
)
ON CONFLICT (username) DO UPDATE
SET
    nama = EXCLUDED.nama,
    pin = EXCLUDED.pin,
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    permissions = EXCLUDED.permissions;


CREATE TABLE IF NOT EXISTS links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('no', 'onproses', 'close')) DEFAULT 'no',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  messages JSONB DEFAULT '[]'::jsonb,
  "order" JSONB DEFAULT '[]'::jsonb
);

-- =================================================================
-- SKEMA DATABASE LOGISTICS STUDIO & BARANG PROMOSI
-- =================================================================
CREATE TABLE IF NOT EXISTS public.jenis (
    id VARCHAR(100) PRIMARY KEY,
    kode VARCHAR(50) NOT NULL,
    nama VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tujuan (
    id VARCHAR(100) PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota VARCHAR(100) DEFAULT '',
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.pengirim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat TEXT DEFAULT '',
    kota_kab VARCHAR(100) DEFAULT '',
    telp VARCHAR(50) DEFAULT '',
    kota_dateline VARCHAR(100) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.documents (
    id VARCHAR(100) PRIMARY KEY,
    nomor_sj VARCHAR(100) NOT NULL UNIQUE,
    jenis_id VARCHAR(100) REFERENCES public.jenis(id) ON DELETE SET NULL,
    tanggal DATE NOT NULL,
    tujuan_id VARCHAR(100) REFERENCES public.tujuan(id) ON DELETE SET NULL,
    up VARCHAR(100) DEFAULT '',
    no_telpon VARCHAR(50) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.items (
    id VARCHAR(100) PRIMARY KEY,
    doc_id VARCHAR(100) REFERENCES public.documents(id) ON DELETE CASCADE,
    rekap_no INT NOT NULL,
    nama_barang VARCHAR(255) NOT NULL,
    ctn INT DEFAULT 0,
    pcs INT DEFAULT 0,
    berat NUMERIC(10,2) DEFAULT 0,
    kubikasi NUMERIC(10,3) DEFAULT 0,
    keterangan TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.promosi (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nomor VARCHAR(100) NOT NULL,
    tgl_terima DATE NOT NULL,
    material TEXT NOT NULL,
    pengirim VARCHAR(255) DEFAULT '',
    penerima VARCHAR(255) DEFAULT '',
    nopol VARCHAR(50) DEFAULT '',
    expedisi VARCHAR(100) DEFAULT '',
    keterangan TEXT DEFAULT '',
    jumlah_ctn INT DEFAULT 0,
    jumlah_pcs INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.rekapan_sj (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    judul VARCHAR(255) NOT NULL,
    tanggal_rekap TIMESTAMPTZ DEFAULT NOW(),
    total_sj INT DEFAULT 0,
    total_item INT DEFAULT 0,
    total_ctn INT DEFAULT 0,
    total_pcs INT DEFAULT 0,
    total_berat NUMERIC(10,2) DEFAULT 0,
    total_kubikasi NUMERIC(10,3) DEFAULT 0,
    data_detail JSONB DEFAULT '[]'::jsonb,
    keterangan TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =================================================================
-- SKEMA TABEL BROADCAST / SIARAN ANTAR PERANGKAT PUBLIK
-- =================================================================
CREATE TABLE IF NOT EXISTS public.broadcast_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'info', -- 'info', 'urgent', 'warning', 'announcement'
    device_info VARCHAR(100) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed User Admin Awal (Khusus Tabel users)
INSERT INTO public.users (username, pin, nama_lengkap, email, password, role, is_active)
VALUES 
  ('admin', '089739', 'Administrator Logistics', 'admin@admin.com', 'Kino.2026', 'admin', true),
  ('dede', '089739', 'Dede Suparman', 'dede.suparman@kino.co.id', 'Kino.2026', 'admin', true)
ON CONFLICT (username) DO UPDATE 
SET 
  pin = EXCLUDED.pin, 
  nama_lengkap = EXCLUDED.nama_lengkap,
  role = EXCLUDED.role,
  is_active = EXCLUDED.is_active;

-- Insert default announcements jika belum ada
INSERT INTO settings (id, messages) 
VALUES ('announcements', '[]'::jsonb) 
ON CONFLICT (id) DO NOTHING;

-- Seed Jenis SJ
INSERT INTO public.jenis (id, kode, nama)
VALUES ('jenis-1', 'CKB', 'SURAT JALAN CKB')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Pengirim
INSERT INTO public.pengirim (nama, alamat, kota_kab, telp, kota_dateline)
SELECT 'LOGISTICS WAREHOUSE', 'Jl. Utama Logistics No. 1', 'Jakarta', '021-12345678', 'Jakarta'
WHERE NOT EXISTS (SELECT 1 FROM public.pengirim);

-- =================================================================
-- SKEMA TABEL RETUR INVENTORY & MONITORING PEMUSNAHAN
-- =================================================================
CREATE TABLE IF NOT EXISTS public.retur_inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    no TEXT,
    item_code TEXT,
    item_name TEXT,
    category TEXT,
    location TEXT,
    location_type TEXT,
    first_qty NUMERIC DEFAULT 0,
    last_qty_pcs NUMERIC DEFAULT 0,
    uom TEXT DEFAULT 'PCS',
    qty_convert_ctn NUMERIC DEFAULT 0,
    uom_convert TEXT DEFAULT 'CTN',
    lpn_serial TEXT,
    batch TEXT,
    vendor_batch TEXT,
    sloc TEXT,
    expired TEXT,
    destination_code TEXT,
    qc_code TEXT,
    user_tally TEXT,
    shelf_life TEXT,
    source TEXT,
    by_ed TEXT
);

-- Pastikan kolom id memiliki default gen_random_uuid jika tabel sudah ada
DO $$
BEGIN
  ALTER TABLE public.retur_inventory ALTER COLUMN id SET DEFAULT gen_random_uuid();
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- Pastikan semua kolom baru terdaftar jika tabel sudah ada sebelumnya
ALTER TABLE public.retur_inventory
  ADD COLUMN IF NOT EXISTS no TEXT,
  ADD COLUMN IF NOT EXISTS item_code TEXT,
  ADD COLUMN IF NOT EXISTS item_name TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS location_type TEXT,
  ADD COLUMN IF NOT EXISTS first_qty NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_qty_pcs NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS uom TEXT DEFAULT 'PCS',
  ADD COLUMN IF NOT EXISTS qty_convert_ctn NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS uom_convert TEXT DEFAULT 'CTN',
  ADD COLUMN IF NOT EXISTS lpn_serial TEXT,
  ADD COLUMN IF NOT EXISTS batch TEXT,
  ADD COLUMN IF NOT EXISTS vendor_batch TEXT,
  ADD COLUMN IF NOT EXISTS sloc TEXT,
  ADD COLUMN IF NOT EXISTS expired TEXT,
  ADD COLUMN IF NOT EXISTS destination_code TEXT,
  ADD COLUMN IF NOT EXISTS qc_code TEXT,
  ADD COLUMN IF NOT EXISTS user_tally TEXT,
  ADD COLUMN IF NOT EXISTS shelf_life TEXT,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS by_ed TEXT;

CREATE TABLE IF NOT EXISTS public.monitoring_pemusnahan (
    id VARCHAR(100) PRIMARY KEY,
    tahun INT NOT NULL,
    bulan_pengajuan VARCHAR(150) NOT NULL,
    qty_pcs NUMERIC(15,2) DEFAULT 0,
    value NUMERIC(18,2) DEFAULT 0,
    cogs NUMERIC(18,2) DEFAULT 0,
    sloc VARCHAR(50) DEFAULT '8A04',
    location VARCHAR(100) DEFAULT 'Cikembar',
    kategori VARCHAR(100) DEFAULT 'REGULER',
    no_persetujuan VARCHAR(150) DEFAULT '',
    no_pengajuan VARCHAR(150) DEFAULT '',
    no_penolakan_qa VARCHAR(150) DEFAULT '',
    approved_head_log VARCHAR(255) DEFAULT '',
    approved_ho_direksi VARCHAR(255) DEFAULT '',
    serah_terima_gudang_reject VARCHAR(255) DEFAULT '',
    acc_teams_bap VARCHAR(255) DEFAULT '',
    kirim_dokumen_bap_ke_ho TEXT DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    musnah_sistem_z87 VARCHAR(255) DEFAULT '',
    completed_approval TEXT DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    completed_ba TEXT DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    completed_migo TEXT DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    sj_kapsul VARCHAR(150) DEFAULT '',
    bap_kapsul VARCHAR(150) DEFAULT '',
    check_kapsul TEXT DEFAULT 'OPEN', -- 'OPEN', 'CLOSE'
    keterangan TEXT DEFAULT '',
    status VARCHAR(50) DEFAULT 'PROSES', -- 'SELESAI', 'PROSES'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_update TIMESTAMPTZ DEFAULT NOW()
);

-- Pastikan kolom tabel monitoring_pemusnahan dapat menampung teks deskriptif
ALTER TABLE public.monitoring_pemusnahan
  ALTER COLUMN kirim_dokumen_bap_ke_ho TYPE TEXT,
  ALTER COLUMN completed_approval TYPE TEXT,
  ALTER COLUMN completed_ba TYPE TEXT,
  ALTER COLUMN completed_migo TYPE TEXT,
  ALTER COLUMN check_kapsul TYPE TEXT;

-- =========================================================
-- AKSES HAK AKSES & RLS (Row Level Security)
-- =========================================================
ALTER TABLE links DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.jenis DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tujuan DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengirim DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.promosi DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rekapan_sj DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcast_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.retur_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_pemusnahan DISABLE ROW LEVEL SECURITY;

-- Berikan izin akses penuh ke anon & authenticated
GRANT ALL ON TABLE public.users TO anon, authenticated;
GRANT ALL ON TABLE public.broadcast_messages TO anon, authenticated;
GRANT ALL ON TABLE public.retur_inventory TO anon, authenticated;
GRANT ALL ON TABLE public.monitoring_pemusnahan TO anon, authenticated;

-- Aktifkan Realtime Replication untuk tabel users, broadcast_messages, retur_inventory, monitoring_pemusnahan
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'users'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'broadcast_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.broadcast_messages;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'retur_inventory'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.retur_inventory;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'monitoring_pemusnahan'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.monitoring_pemusnahan;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'data_pemusnahan'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.data_pemusnahan;
  END IF;
EXCEPTION WHEN OTHERS THEN
  -- Abaikan jika publication supabase_realtime belum aktif atau sudah ada
  NULL;
END $$;

-- =========================================================
-- TABEL DATA PEMUSNAHAN (26 KOLOM DETAIL BARANG / SPREADSHEET GAS)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.data_pemusnahan (
    id VARCHAR(100) PRIMARY KEY,
    id_pemusnahan VARCHAR(100) NOT NULL,
    item_code VARCHAR(100) NOT NULL,
    nama_barang VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) DEFAULT '-',
    lokasi VARCHAR(100) DEFAULT '-',
    tipe_lokasi VARCHAR(100) DEFAULT '-',
    qty_awal NUMERIC(15,2) DEFAULT 0,
    qty_akhir NUMERIC(15,2) DEFAULT 0,
    uom VARCHAR(50) DEFAULT 'PCS',
    qty_convert NUMERIC(15,2) DEFAULT 0,
    uom_convert VARCHAR(50) DEFAULT '-',
    lpn_sn VARCHAR(100) DEFAULT '-',
    batch VARCHAR(100) DEFAULT '-',
    vendor_batch VARCHAR(100) DEFAULT '-',
    sloc VARCHAR(50) DEFAULT '8A03',
    expired_date VARCHAR(100) DEFAULT '-',
    kode_tujuan VARCHAR(100) DEFAULT '-',
    status_qc VARCHAR(100) DEFAULT '-',
    user_tally VARCHAR(100) DEFAULT '-',
    shelf_life VARCHAR(100) DEFAULT '-',
    sumber VARCHAR(100) DEFAULT '-',
    tujuan VARCHAR(150) DEFAULT '-',
    user_input VARCHAR(150) DEFAULT '-',
    tanggal_update VARCHAR(100) DEFAULT '-',
    status VARCHAR(100) DEFAULT '-',
    catatan TEXT DEFAULT '-',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index performa pencarian & filter
CREATE INDEX IF NOT EXISTS idx_data_pms_id_pms ON public.data_pemusnahan(id_pemusnahan);
CREATE INDEX IF NOT EXISTS idx_data_pms_item_code ON public.data_pemusnahan(item_code);
CREATE INDEX IF NOT EXISTS idx_data_pms_batch ON public.data_pemusnahan(batch);
CREATE INDEX IF NOT EXISTS idx_data_pms_sloc ON public.data_pemusnahan(sloc);
CREATE INDEX IF NOT EXISTS idx_data_pms_tujuan ON public.data_pemusnahan(tujuan);

-- Hak akses & RLS
ALTER TABLE public.data_pemusnahan DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.data_pemusnahan TO anon, authenticated;





